version: '3.8'

services:
  backend:
    build: .
    env_file: ./.env
    image: football_schedule_backend
    container_name: backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL-AUTO: validate
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ../footballUI/frontend  # Укажите путь к папке фронтенда
      dockerfile: Dockerfile
    image: football_schedule_frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8080  # Для доступа к API бэкенда