version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    env_file: ./.env
    image: football_schedule_backend
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL-AUTO: validate
    ports:
      - "8080:8080"


  frontend:
    build:
      context: ../footballUI/frontend  # Укажите путь к папке фронтенда
      dockerfile: Dockerfile
    image: football_schedule_frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      - db
    environment:
      - REACT_APP_API_URL=http://backend:8080  # Для доступа к API бэкенда

volumes:
  postgres_data: