# ?? ? Docker (?? ????? ???????)
spring.datasource.url=jdbc:postgresql://db:5432/${DB_NAME}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# ? Docker SQL-???? ?????? ?? ?????
spring.jpa.show-sql=false

# ? Docker health ?????????? ?????? ?????? ?????? ????
management.endpoint.health.show-details=never

# ???? ? ?????????? (???, ??? EXPOSE ? Dockerfile)
server.port=8080

# ??? (????? redis ????? ????????)
spring.cache.type=simple