# ????????? ?? (?? ?????)
spring.datasource.url=jdbc:postgresql://localhost:5432/football_schedule
spring.datasource.username=postgres
spring.datasource.password=postgres

# ?????????? SQL ? ??????? (?????? ??? ???????)
spring.jpa.show-sql=true

# ????? ????????? health ??? ??????????
management.endpoint.health.show-details=always

# ???? (?????? ???????? 8081 ??? local)
server.port=8081

# ??? (simple ??? ????????? ??????????)
spring.cache.type=simple